### ISSUE TITLE
Drill core detail view tabs

### ISSUE THREAD

**Issue by enmust** [geocollections/GRIS#11]
drillcore_box, locality_description, locality_reference, attachments, samples, analyses

**Comment by Erikdzo** [comment]
- [x] drillcore_box
- [x] locality_description
- [x] locality_reference
- [ ] attachments
- [ ] samples
- [ ] analyses

**Comment by enmust** [comment]
sample: ID, sample number, depth, depth interval, stratigraphy, agent collected, date collected, 

analysis: id, sample number, depth, depth interval, method, method details, person/inst, analyzed by, date

**Comment by enmust** [comment]
Attachments: both locality and drillcore

**Comment by enmust** [comment]
Specimen tab

**Comment by enmust** [comment]
Request should be made through locality
