### ISSUE TITLE
Drillcore view ideas

### ISSUE THREAD

**Issue by ollehints** [geocollections/GRIS#13]
Locality section should include additional fields after Longitude:
Elevation / kõrgus (field epsg)
X (field coordx)
Y (field coordx)
EPSG (field epsg)

Solve problems with static images not shown. Is it OK that they come from https://geocollections.info/_nuxt/img/... folder?
Footer text and logos may differ from geocollections.info. For now we can remove DataCite and KIK logos from GRIS components and set preliminary texts:
2021 GRIS: Geoloogia portaal (testversioon).
2021 GRIS: Geology portal (preview version).

**Descriptions tab** should include fields:
depth_base, depth_top, rock__name/rock__name_en, stratigraphy__stratigraphy/stratigraphy__stratigraphy_en, description
Default paging 25, other options 10, 50, 100
In the future if descriptions will get longer and all fields cannot be shown nicely in tabel, then we should open full data in modal popup or perhaps new vindow.

**References tab** should include field from reference: reference__title, after reference__reference then pages and then remarks.
Default paging 25, other options 10, 50, 100
Links should open in new window.

**Map**
If locality__country__value='Estonia' use Estonian base map by default, otherwise use openstreetmap. 
Show popup window with Locality name for marker.

**Comment by enmust** [comment]
> Is it OK that they come from https://geocollections.info/_nuxt/img/... folder?

@ollehints This is fine, all nuxt files come from this folder, we can rename it if needed but that shouldn't make a difference.

**Comment by Erikdzo** [comment]
Static images should work now. Problem was with .gitattributes file, it was not configured for .png files. Because of that it read them as text when pushing to GitHub and corrupted every png file.

**Comment by Erikdzo** [comment]
Added fields to refernece tab
