### ISSUE TITLE
Description data hidden on sort

### ISSUE THREAD

**Issue by ollehints** [geocollections/GRIS#30]
If user opens a drill core description (sorted by depth_top and depth_base by default) and clicks Description header to add additional sort criterion, then all rows get hidden. example record: https://geocollections.info/drillcore/490/locality_description.

**Comment by Erikdzo** [comment]
Description sort is not configured for locality_description table in API.

**Comment by Erikdzo** [comment]
Same happens when sorting in the attachment table using author. Adding 'attachment__author_agent' to attachment_link API config should fix the problem.

**Comment by enmust** [comment]
Config updated
